### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by danielgomezrico** [ilikerobots/fluttericon_pkg#4]
I have some questions around this library, Is there any performance gain between:
- having this vs having all of the icons in `.svg`? 
- Using the `.ttf` format itself?

I see a warning in the readme that says that it should not be used in production, it refers to the material iconset and not the hole library right?:

```
Please note this package is not intended for production use, due to the large size. Instead, it can be used as a development aid to help identify/test icons.

For production use, it is highly recommended to use FlutterIcon to customize your icon pack, limiting your icon font to needed icons and building your own from custom SVG.
```

I already asked there but I am not getting any responses:
https://stackoverflow.com/questions/65628990/is-there-any-performance-gain-with-fluttericons-instead-of-using-the-svg-directl

**Comment by ilikerobots** [comment]
The reason for the warning is that it would unnecessarily increase the physical size of an app to include all 4000+ icons, assuming the vast majority of those are not needed in the actual app UI.   Whether this increased size has any effect on performance, I do not know.

In any case, it would be better to use https://www.fluttericon.com/, which generates the same package structure as fluttericon_pkg, to customize your icon font to include only your needed icons.

**Comment by danielgomezrico** [comment]
@ilikerobots but the question goes beyond to ask if  fluttericon.com adds some performance or advantages gain vs just using the plain .svg

**Comment by ilikerobots** [comment]
@danielgomezrico, A fluttericon generated package is implemented via Flutter's `IconData` font glyph engine in the same (as far as I am aware) way as [Flutter's built-in material Icons](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/icons.dart)

For that reason, I think a big part of the question is not specific to Fluttericon, but to Flutter's implementation of font glyph icons vs svg.  I'm afraid I have no insight into the relative performance of the two but there may be research or experts elsewhere that could lead to an answer.

Re the remaining part of the question ("Does Fluttericon introduce perf concerns beyond Flutter's basic font glyph engine?"), I'll say that I am unaware of any reason the perf from a fluttericon generated `IconData` font glyph would be different from any other font glyph.  Having said that, it's not impossible (poorly optimized svg? nuances in organization of the TTF?)  While I don't think it's likely (as the Flutter docs don't mention these concerns), in the absence of real tests/benchmarks a solid answer is impossible.

**Comment by danielgomezrico** [comment]
Thanks for that answer! now it is more clear to me how this works, I will come back if I found something in the future.
